"""empty message

Revision ID: 62d1ce43134b
Revises: f9941ebc228d
Create Date: 2025-02-02 19:24:43.884309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d1ce43134b'
down_revision = 'f9941ebc228d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.alter_column('good_transcript',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=15000),
               existing_nullable=False)
        batch_op.alter_column('bad_transcript',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=15000),
               existing_nullable=False)

    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('user_transcript',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=15000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('user_transcript',
               existing_type=sa.String(length=15000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)

    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.alter_column('bad_transcript',
               existing_type=sa.String(length=15000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)
        batch_op.alter_column('good_transcript',
               existing_type=sa.String(length=15000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###
