"""Add overall_score, testing_id and summary to UserTranscript

Revision ID: a7160ceef5a5
Revises: cd26fc68aefe
Create Date: 2025-02-21 15:24:21.240396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7160ceef5a5'
down_revision = 'cd26fc68aefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=15000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('overall_score')
        batch_op.drop_column('testing_id')

    # ### end Alembic commands ###
