"""empty message

Revision ID: b08f1f8bfa5b
Revises: e895ff39bd4b
Create Date: 2025-02-07 09:52:51.741646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08f1f8bfa5b'
down_revision = 'e895ff39bd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('srt_file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.drop_column('srt_file_path')

    # ### end Alembic commands ###
