"""change testing_id to string in UserTranscriptions

Revision ID: b62d2de8a7e3
Revises: a7160ceef5a5
Create Date: 2025-02-21 16:54:44.434930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62d2de8a7e3'
down_revision = 'a7160ceef5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('testing_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('testing_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
