"""update transcript model

Revision ID: d5c1c79ab52f
Revises: 016429e92fb9
Create Date: 2025-03-03 11:43:21.749440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c1c79ab52f'
down_revision = '016429e92fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benchmark_score', sa.Float(), nullable=True))

    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.drop_column('benchmark_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benchmark_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('transcript_test', schema=None) as batch_op:
        batch_op.drop_column('benchmark_score')

    # ### end Alembic commands ###
