"""some descrition of migration

Revision ID: e0fe689bf779
Revises: b95a7d685504
Create Date: 2025-02-05 09:58:11.535273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0fe689bf779'
down_revision = 'b95a7d685504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=15000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transcript', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.String(length=15000),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
