"""fix foreign key issue

Revision ID: f9941ebc228d
Revises: 0116ab1178e8
Create Date: 2025-02-02 19:09:11.747717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9941ebc228d'
down_revision = '0116ab1178e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_transcript', sa.String(length=1500), nullable=False),
    sa.Column('bad_transcript', sa.String(length=1500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('test_taken', sa.Integer(), nullable=False),
    sa.Column('user_transcript', sa.String(length=1500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_taken'], ['transcript_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_transcript')
    op.drop_table('transcript_test')
    # ### end Alembic commands ###
